---
layout: post
title: "WIPO Open Source Patent Analytics: The Manual by Chapter"
author: "Paul Oldham"
date: "17 November 2015"
published: true
---

This document provides links to the chapters in the [WIPO Manual on Open Source Patent Analytics](http://poldham.github.io). The chapters can be accessed online at the [project website](http://poldham.github.io), and in `pdf`, `Word` and `raw html` formats. Note that these are the advanced unedited versions of the chapters and further work will be carried out on formatting and corrections to produce the final version. 

1. About the Open Source Patent Analytics Project
[online](http://poldham.github.io/About-the-Project/) [pdf](https://github.com/poldham/opensource-patent-analytics/raw/master/5_the_manual_files/pdf_versions/1-About-the-Project.pdf) [word](https://github.com/poldham/opensource-patent-analytics/raw/master/5_the_manual_files/word_versions/1.%20About-the-Project.doc) [html](https://raw.githubusercontent.com/poldham/opensource-patent-analytics/master/5_the_manual_files/html_versions/1-About-the-Project.html)

2. An Overview of Open Source Tools for Patent Analytics
[online](http://poldham.github.io/overview-open-tools/) [pdf](https://github.com/poldham/opensource-patent-analytics/raw/master/5_the_manual_files/pdf_versions/2-overview-open-tools.pdf) [word](https://github.com/poldham/opensource-patent-analytics/raw/master/5_the_manual_files/word_versions/2-overview-open-tools.doc) [html](https://github.com/poldham/opensource-patent-analytics/blob/master/5_the_manual_files/html_versions/2-overview-open-tools.html?raw=true)

3. Understanding Patent Documents and Data Fields
[online](http://poldham.github.io/Patent-Data-Fields/) [pdf](https://github.com/poldham/opensource-patent-analytics/raw/master/5_the_manual_files/pdf_versions/3-Patent-Data-Fields.pdf) [word](https://github.com/poldham/opensource-patent-analytics/raw/master/5_the_manual_files/word_versions/3-Patent-Data-Fields.doc) [html](https://raw.githubusercontent.com/poldham/opensource-patent-analytics/master/5_the_manual_files/html_versions/3-Patent-Data-Fields.html) 

4. Patent Analytics Training Datasets
[online](http://poldham.github.io/Patent-Datasets/) [pdf](https://github.com/poldham/opensource-patent-analytics/raw/master/5_the_manual_files/pdf_versions/4-Patent-Datasets.pdf) [word](https://github.com/poldham/opensource-patent-analytics/raw/master/5_the_manual_files/word_versions/4-Patent-Datasets.docx) [html](https://github.com/poldham/opensource-patent-analytics/raw/master/5_the_manual_files/html_versions/4-Patent-Datasets.html)

5. Obtaining Patent Data: Patent Databases
[online](http://poldham.github.io/Patent-Databases/) [pdf](https://github.com/poldham/opensource-patent-analytics/raw/master/5_the_manual_files/pdf_versions/5-Patent-Databases.pdf) [word](https://github.com/poldham/opensource-patent-analytics/raw/master/5_the_manual_files/word_versions/5-Patent-Databases.docx) [html](https://github.com/poldham/opensource-patent-analytics/raw/master/5_the_manual_files/html_versions/5-Patent-Databases.html) 

6. Obtaining Patent Data: WIPO Patentscope
[online](http://poldham.github.io/patentscope/) [pdf](https://github.com/poldham/opensource-patent-analytics/raw/master/5_the_manual_files/pdf_versions/6-patentscope.pdf) [word](https://github.com/poldham/opensource-patent-analytics/raw/master/5_the_manual_files/word_versions/6-patentscope.docx) [html](https://github.com/poldham/opensource-patent-analytics/raw/master/5_the_manual_files/html_versions/6-patentscope.html) 

7. Using Patent2Net to Obtain Patent Data
[online](http://poldham.github.io/Patent2Net_Patent_Analytics/) [pdf](https://github.com/poldham/opensource-patent-analytics/raw/master/5_the_manual_files/pdf_versions/7-Patent2Net_Patent_Analytics.pdf) [word](https://github.com/poldham/opensource-patent-analytics/raw/master/5_the_manual_files/word_versions/7-Patent2Net_Patent_Analytics.docx) [html](https://github.com/poldham/opensource-patent-analytics/raw/master/5_the_manual_files/html_versions/7-Patent2Net_Patent_Analytics.html)

8. Cleaning Patent Data with Open Refine
[online](http://poldham.github.io/openrefine-patent-cleaning/) [pdf](https://github.com/poldham/opensource-patent-analytics/raw/master/5_the_manual_files/pdf_versions/8-openrefine-patent-cleaning.pdf) [word](https://github.com/poldham/opensource-patent-analytics/raw/master/5_the_manual_files/word_versions/8-openrefine-patent-cleaning.docx) [html](https://github.com/poldham/opensource-patent-analytics/raw/master/5_the_manual_files/html_versions/8-openrefine-patent-cleaning.html) 

9. Visualising Patent Data in Tableau Public
[online](http://poldham.github.io/tableau-patents/) [pdf](https://github.com/poldham/opensource-patent-analytics/raw/master/5_the_manual_files/pdf_versions/9-tableau-patents.pdf) [word](https://github.com/poldham/opensource-patent-analytics/raw/master/5_the_manual_files/word_versions/9-tableau-patents.doc) [html](https://github.com/poldham/opensource-patent-analytics/raw/master/5_the_manual_files/html_versions/9-tableau-patents.html) 

10. Patent Network Visualization with Gephi
[online](http://poldham.github.io/gephi_patent_network/) [pdf](https://github.com/poldham/opensource-patent-analytics/raw/master/5_the_manual_files/pdf_versions/10-gephi_patent_network.pdf) [word](https://github.com/poldham/opensource-patent-analytics/raw/master/5_the_manual_files/word_versions/10-gephi_patent_network.docx) [html](https://github.com/poldham/opensource-patent-analytics/raw/master/5_the_manual_files/html_versions/10-gephi_patent_network.html) 

11. An Introduction to Plotly for Patent Analytics
[online](http://poldham.github.io/plotly/) [pdf](https://github.com/poldham/opensource-patent-analytics/raw/master/5_the_manual_files/pdf_versions/11-plotly_copy.pdf) [word](https://github.com/poldham/opensource-patent-analytics/raw/master/5_the_manual_files/word_versions/11-plotly_copy.docx) [html](https://github.com/poldham/opensource-patent-analytics/raw/master/5_the_manual_files/html_versions/11-plotly.html) 

12. Importing csv files into R
[online](http://poldham.github.io/reading-csv-files-in-R/) [pdf](https://github.com/poldham/opensource-patent-analytics/raw/master/5_the_manual_files/pdf_versions/12-reading-csv-files-in-R.pdf) [word](https://github.com/poldham/opensource-patent-analytics/raw/master/5_the_manual_files/word_versions/12-reading-csv-files-in-R.docx) [html](https://github.com/poldham/opensource-patent-analytics/raw/master/5_the_manual_files/html_versions/12-reading-csv-files-in-R.html) 

13. Reading and Writing an Excel File in R
[online](http://poldham.github.io/reading-writing-excel-files-R/) [pdf](https://github.com/poldham/opensource-patent-analytics/raw/master/5_the_manual_files/pdf_versions/13-reading-writing-excel-files-R.pdf) [word](https://github.com/poldham/opensource-patent-analytics/raw/master/5_the_manual_files/word_versions/13-reading-writing-excel-files-R.docx) [html](https://github.com/poldham/opensource-patent-analytics/raw/master/5_the_manual_files/html_versions/13-reading-writing-excel-files-R.html))

14. Introducing R and Graphing Pizza Patents: Part 1
[online](http://poldham.github.io/ggplot_pizza_patents_part1/) [pdf](https://github.com/poldham/opensource-patent-analytics/raw/master/5_the_manual_files/pdf_versions/14-ggplot_pizza_patents_part1.pdf) [word](https://github.com/poldham/opensource-patent-analytics/raw/master/5_the_manual_files/word_versions/14-ggplot_pizza_patents_part1.docx) [html](https://github.com/poldham/opensource-patent-analytics/raw/master/5_the_manual_files/html_versions/14-ggplot_pizza_patents_part1.html)

15. Introducing R and Graphing Patent Data with ggplot2: Part 2
[online](http://poldham.github.io/ggplot_pizza_patents_part2j/) [pdf](https://github.com/poldham/opensource-patent-analytics/raw/master/5_the_manual_files/pdf_versions/15-ggplot_pizza_patents_part2.pdf) [word](https://github.com/poldham/opensource-patent-analytics/raw/master/5_the_manual_files/word_versions/15-ggplot_pizza_patents_part2.docx) [html](https://github.com/poldham/opensource-patent-analytics/raw/master/5_the_manual_files/html_versions/15-ggplot_pizza_patents_part2.html)

16. Accessing Scientific Literature with the rplos package in R
[online](http://poldham.github.io/rplos-walkthrough/) [pdf](https://github.com/poldham/opensource-patent-analytics/raw/master/5_the_manual_files/pdf_versions/16-rplos-walkthrough.pdf) [word](https://github.com/poldham/opensource-patent-analytics/raw/master/5_the_manual_files/word_versions/16-rplos-walkthrough.docx) [html](https://github.com/poldham/opensource-patent-analytics/raw/master/5_the_manual_files/html_versions/16-rplos-walkthrough.html) 
