---
layout: post
title: "Open Source Patent Analytics Survey"
author: "Paul Oldham"
date: "17 May 2015"
tags: [open source software, patent analysis, patent analytics, patent survey, WIPO]
published: true
---

Patent researchers and professionals are increasingly using open source and free software tools as part of their work. We are working to develop a WIPO Manual on open source and free software tools with support from the [WIPO Secretariat](http://www.wipo.int/patentscope/en/programs/patent_landscapes/). The idea is to identify existing tools and develop materials that will help researchers and professionals to work with these tools in common patent analysis tasks.

We would like to ask for your help with understanding the tools that people are already using. We would also like to find out what difficulties people encounter in working with patent data and what people would like to see in the future.

To do this we have developed a short 10 minute survey [here](https://www.surveymonkey.com/s/NFFRZR6). We would greatly appreciate it if you would participate in the survey. We will then anonymise the data and share the results with the group.

We are getting started with developing materials which will be hosted on GitHub to provide open access. People who are interested in contributing can also join in through the [GitHub repository](https://github.com/poldham/opensource-patent-analytics) or by [emailing me](mailto:opensourcepatentanalytics@gmail.com) with suggestions. 

Many thanks in advance for participating.

Kind regards, 

Paul Oldham (Ph.D.)



- Updated: new
- Written in: [RStudio](http://www.rstudio.com) with a little help from [Scrivener](https://www.literatureandlatte.com/scrivener.php).
